spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: host_route
        uri: http://${HOST:localhost}
        predicates:
        - Path=/contract/**/file
        filters:
        - RewritePath=/contract/(?<segment>.*)/file, /$\{segment}



  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}
logging:
    level:
      org:
        springframework:
          cloud:
            sleuth=DEBUG